eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${EUREKA_SERVER_PORT}/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: INFO