server:
  port: 8085

spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/
    enabled: true
    fetchRegistry: true
    registerWithEureka: true

  instance:
    preferIpAddress: true
    hostname: ${EUREKA_SERVER_HOSTNAME}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: INFO