server:
  port: 8085

spring:
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka/
  instance:
    preferIpAddress: true
    hostname: ${EUREKA_SERVER_HOSTNAME}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: INFO